### ISSUE TITLE
Combine with Kim Jong-Il images?

### ISSUE THREAD

**Issue by faaip** [lduck11007/kim-jong-un-dataset#4]
Great work! I have scraped quite a few images of Kim Jong-Il. Would you be interested in a pull request?

**Comment by leowhitehead** [comment]
I would greatly appreciate a pull request to extend this dataset. Although if you're including Kim Jong-il, please ensure that these images are separate to those of Supreme Leader Kim Jong-un, so as not to corrupt the dataset. Thanks.

**Comment by faaip** [comment]
Great! I added a [pull request](https://github.com/lduck11007/kim-jong-un-dataset/issues/4)
